#!/bin/bash

echo "Updating directories..."

cd /
sudo apt update -y
sudo apt updgrade -y

echo "Process finished!"

echo "Starting the web server installation..."

sudo apt install apache2 -y
sudo apt install unzip -y

echo "Downloading site content and copying to apache directorie."

cd /tmp
wget https://github.com/denilsonbonatti/linux-site-dio/archive/refs/heads/main.zip
cd linux-site-dio-main

cp -R * /var/www/html

echo "Finished."
